/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.slick)
    implementation(libs.lwjgl)
    implementation(libs.lwjgl.util)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(7)
    }
}

application {
    // Define the main class for the application.
    mainClass = "game.Main"
}

tasks.named<JavaExec>("run") {
    jvmArgs(
        "-Djava.library.path=${project.rootDir}/native/macosx",
        "-Dsun.java2d.d3d=false"
    )

    args(
        "-param",
        "-path:./_FarSky/",
        "-logPath:./_FarSky/log/",
        "-windowMode"
    )
}
